# http:
#   use_x_forwarded_for: true
#   trusted_proxies:
#     - 192.168.49.1
#     - 172.0.0.1
#   server_port: 8443

panel_iframe:
  portainer:
    title: "Portainer"
    url: "https://localhost:9443/#!/home"
    icon: mdi:docker
    require_admin: true

  # tasmotaadmin:
  #   title: "Tasmota Admin"
  #   url: "http://localhost:9000"
  #   icon: mdi:tasmota
  #   require_admin: true

  # plex:
  #   title: "Plex"
  #   url: "http://localhost:32400/web"
  #   icon: mdi:plex
  #   require_admin: true

  vscode:
    title: Visual Studio Code
    icon: mdi:visual-studio-code
    url: http://localhost:8443/  

  # nodered:
  #   title: Node-Red
  #   icon: mdi:node-red
  #   url: http://localhost:1880/ 

# Loads default set of integrations. Do not remove.
default_config:

influxdb:
  host: 192.168.15.9
  port: 8086
  database: homeassistant
  ssl: false
  max_retries: 3
  default_measurement: state
  include:
    domains:
      - sensor
      - binary_sensor
      - sun
    entities:
      - sensor.luz_escritorio_power
      - sensor.luz_escritorio_current
      - sensor.luz_escritorio_voltage

sensor:
  - platform: command_line
    name: "Download Grafana"
    command: curl -s -H "Authorization=Bearer <TOKEN>" "http://192.168.15.9:3000/render/d-solo/GGSGtJzgk/tuya-energy-monitoring?from=1676835475044&to=1676921875044&orgId=1&panelId=9&width=1000&height=500&tz=America%2FSao_Paulo" > /config/downloads/current_usage.png

camera:
  - platform: local_file
    name: crafana_Current_usage
    file_path: /config/downloads/current_usage.png

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
